ALTER TABLE tasks ADD COLUMN IF NOT EXISTS task_date DATE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS start_time TIME;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS end_time TIME;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS duration_hours NUMERIC(4,2);
